remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Manuel Gortarez]
descriptions: [Here you can find some of my projects that I've made in my collegue.]
